FROM ubuntu:focal

ENV \
    NODE_ENV="production" \
    CHOKIDAR_USEPOLLING=1 \
    CHOKIDAR_INTERVAL=500

RUN set -ex; \
    export DEBIAN_FRONTEND=noninteractive; \
    groupadd -r node; \
    useradd -r -g node node; \
    apt-get -qq update; \
    apt-get -y --no-install-recommends install \
      ca-certificates \
      wget; \
    wget -qO- https://deb.nodesource.com/setup_18.x | bash; \
    apt-get install -y nodejs; \
    apt-get -y remove wget; \
    apt-get -y --purge autoremove; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*;

EXPOSE 8080

RUN mkdir -p /data; \
    chown node:node /data; \
    mkdir -p /usr/src/app;

VOLUME /data

WORKDIR /data

COPY / /usr/src/app

RUN cd /usr/src/app; \
    npm install --omit=dev; \
    chown -R root:root /usr/src/app; \
    chmod +x /usr/src/app/docker-entrypoint.sh;

USER node:node

ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]

HEALTHCHECK CMD node /usr/src/app/src/healthcheck.js